import React from "react";

import { motion } from "framer-motion";



export const ConcatsPage = () => {
	return (
		<motion.section
			initial={{ transform: 'translateY(100%)', opacity: 0 }}
			animate={{ transform: 'translateY(0%)', opacity: 1 }}
			exit={{ transform: 'translateY(100%)', opacity: 0, transition: { duration: 0.1 } }}
			className="page__contacts contacts-page"
		>
			<div className="contacts-page__container _container">
				<h1>Котакты</h1>
				<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, voluptatem, laudantium reiciendis voluptate illum error quisquam eum iure odio ipsum temporibus corrupti doloribus itaque animi est aliquid a, laborum consequuntur! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque, obcaecati facilis vel adipisci odit amet voluptas consequatur reiciendis dolores. Tenetur dicta, iusto ea ipsa quis repellat numquam enim quae perspiciatis.</p>
				<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, voluptatem, laudantium reiciendis voluptate illum error quisquam eum iure odio ipsum temporibus corrupti doloribus itaque animi est aliquid a, laborum consequuntur! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque, obcaecati facilis vel adipisci odit amet voluptas consequatur reiciendis dolores. Tenetur dicta, iusto ea ipsa quis repellat numquam enim quae perspiciatis.</p>
				<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, voluptatem, laudantium reiciendis voluptate illum error quisquam eum iure odio ipsum temporibus corrupti doloribus itaque animi est aliquid a, laborum consequuntur! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque, obcaecati facilis vel adipisci odit amet voluptas consequatur reiciendis dolores. Tenetur dicta, iusto ea ipsa quis repellat numquam enim quae perspiciatis.</p>
				<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, voluptatem, laudantium reiciendis voluptate illum error quisquam eum iure odio ipsum temporibus corrupti doloribus itaque animi est aliquid a, laborum consequuntur! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque, obcaecati facilis vel adipisci odit amet voluptas consequatur reiciendis dolores. Tenetur dicta, iusto ea ipsa quis repellat numquam enim quae perspiciatis.</p>
				<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, voluptatem, laudantium reiciendis voluptate illum error quisquam eum iure odio ipsum temporibus corrupti doloribus itaque animi est aliquid a, laborum consequuntur! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque, obcaecati facilis vel adipisci odit amet voluptas consequatur reiciendis dolores. Tenetur dicta, iusto ea ipsa quis repellat numquam enim quae perspiciatis.</p>
				<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, voluptatem, laudantium reiciendis voluptate illum error quisquam eum iure odio ipsum temporibus corrupti doloribus itaque animi est aliquid a, laborum consequuntur! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque, obcaecati facilis vel adipisci odit amet voluptas consequatur reiciendis dolores. Tenetur dicta, iusto ea ipsa quis repellat numquam enim quae perspiciatis.</p>
				<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, voluptatem, laudantium reiciendis voluptate illum error quisquam eum iure odio ipsum temporibus corrupti doloribus itaque animi est aliquid a, laborum consequuntur! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque, obcaecati facilis vel adipisci odit amet voluptas consequatur reiciendis dolores. Tenetur dicta, iusto ea ipsa quis repellat numquam enim quae perspiciatis.</p>
				<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, voluptatem, laudantium reiciendis voluptate illum error quisquam eum iure odio ipsum temporibus corrupti doloribus itaque animi est aliquid a, laborum consequuntur! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque, obcaecati facilis vel adipisci odit amet voluptas consequatur reiciendis dolores. Tenetur dicta, iusto ea ipsa quis repellat numquam enim quae perspiciatis.</p>
				<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, voluptatem, laudantium reiciendis voluptate illum error quisquam eum iure odio ipsum temporibus corrupti doloribus itaque animi est aliquid a, laborum consequuntur! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque, obcaecati facilis vel adipisci odit amet voluptas consequatur reiciendis dolores. Tenetur dicta, iusto ea ipsa quis repellat numquam enim quae perspiciatis.</p>
				<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, voluptatem, laudantium reiciendis voluptate illum error quisquam eum iure odio ipsum temporibus corrupti doloribus itaque animi est aliquid a, laborum consequuntur! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque, obcaecati facilis vel adipisci odit amet voluptas consequatur reiciendis dolores. Tenetur dicta, iusto ea ipsa quis repellat numquam enim quae perspiciatis.</p>
				<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, voluptatem, laudantium reiciendis voluptate illum error quisquam eum iure odio ipsum temporibus corrupti doloribus itaque animi est aliquid a, laborum consequuntur! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque, obcaecati facilis vel adipisci odit amet voluptas consequatur reiciendis dolores. Tenetur dicta, iusto ea ipsa quis repellat numquam enim quae perspiciatis.</p>
				<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, voluptatem, laudantium reiciendis voluptate illum error quisquam eum iure odio ipsum temporibus corrupti doloribus itaque animi est aliquid a, laborum consequuntur! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque, obcaecati facilis vel adipisci odit amet voluptas consequatur reiciendis dolores. Tenetur dicta, iusto ea ipsa quis repellat numquam enim quae perspiciatis.</p>
				<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, voluptatem, laudantium reiciendis voluptate illum error quisquam eum iure odio ipsum temporibus corrupti doloribus itaque animi est aliquid a, laborum consequuntur! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque, obcaecati facilis vel adipisci odit amet voluptas consequatur reiciendis dolores. Tenetur dicta, iusto ea ipsa quis repellat numquam enim quae perspiciatis.</p>
				<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, voluptatem, laudantium reiciendis voluptate illum error quisquam eum iure odio ipsum temporibus corrupti doloribus itaque animi est aliquid a, laborum consequuntur! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque, obcaecati facilis vel adipisci odit amet voluptas consequatur reiciendis dolores. Tenetur dicta, iusto ea ipsa quis repellat numquam enim quae perspiciatis.</p>
				<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, voluptatem, laudantium reiciendis voluptate illum error quisquam eum iure odio ipsum temporibus corrupti doloribus itaque animi est aliquid a, laborum consequuntur! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque, obcaecati facilis vel adipisci odit amet voluptas consequatur reiciendis dolores. Tenetur dicta, iusto ea ipsa quis repellat numquam enim quae perspiciatis.</p>
				<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, voluptatem, laudantium reiciendis voluptate illum error quisquam eum iure odio ipsum temporibus corrupti doloribus itaque animi est aliquid a, laborum consequuntur! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque, obcaecati facilis vel adipisci odit amet voluptas consequatur reiciendis dolores. Tenetur dicta, iusto ea ipsa quis repellat numquam enim quae perspiciatis.</p>
				<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, voluptatem, laudantium reiciendis voluptate illum error quisquam eum iure odio ipsum temporibus corrupti doloribus itaque animi est aliquid a, laborum consequuntur! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque, obcaecati facilis vel adipisci odit amet voluptas consequatur reiciendis dolores. Tenetur dicta, iusto ea ipsa quis repellat numquam enim quae perspiciatis.</p>
				<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, voluptatem, laudantium reiciendis voluptate illum error quisquam eum iure odio ipsum temporibus corrupti doloribus itaque animi est aliquid a, laborum consequuntur! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque, obcaecati facilis vel adipisci odit amet voluptas consequatur reiciendis dolores. Tenetur dicta, iusto ea ipsa quis repellat numquam enim quae perspiciatis.</p>
				<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, voluptatem, laudantium reiciendis voluptate illum error quisquam eum iure odio ipsum temporibus corrupti doloribus itaque animi est aliquid a, laborum consequuntur! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque, obcaecati facilis vel adipisci odit amet voluptas consequatur reiciendis dolores. Tenetur dicta, iusto ea ipsa quis repellat numquam enim quae perspiciatis.</p>
				<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, voluptatem, laudantium reiciendis voluptate illum error quisquam eum iure odio ipsum temporibus corrupti doloribus itaque animi est aliquid a, laborum consequuntur! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque, obcaecati facilis vel adipisci odit amet voluptas consequatur reiciendis dolores. Tenetur dicta, iusto ea ipsa quis repellat numquam enim quae perspiciatis.</p>
				<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, voluptatem, laudantium reiciendis voluptate illum error quisquam eum iure odio ipsum temporibus corrupti doloribus itaque animi est aliquid a, laborum consequuntur! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque, obcaecati facilis vel adipisci odit amet voluptas consequatur reiciendis dolores. Tenetur dicta, iusto ea ipsa quis repellat numquam enim quae perspiciatis.</p>
				<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, voluptatem, laudantium reiciendis voluptate illum error quisquam eum iure odio ipsum temporibus corrupti doloribus itaque animi est aliquid a, laborum consequuntur! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque, obcaecati facilis vel adipisci odit amet voluptas consequatur reiciendis dolores. Tenetur dicta, iusto ea ipsa quis repellat numquam enim quae perspiciatis.</p>
				<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, voluptatem, laudantium reiciendis voluptate illum error quisquam eum iure odio ipsum temporibus corrupti doloribus itaque animi est aliquid a, laborum consequuntur! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque, obcaecati facilis vel adipisci odit amet voluptas consequatur reiciendis dolores. Tenetur dicta, iusto ea ipsa quis repellat numquam enim quae perspiciatis.</p>
				<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, voluptatem, laudantium reiciendis voluptate illum error quisquam eum iure odio ipsum temporibus corrupti doloribus itaque animi est aliquid a, laborum consequuntur! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque, obcaecati facilis vel adipisci odit amet voluptas consequatur reiciendis dolores. Tenetur dicta, iusto ea ipsa quis repellat numquam enim quae perspiciatis.</p>
				<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, voluptatem, laudantium reiciendis voluptate illum error quisquam eum iure odio ipsum temporibus corrupti doloribus itaque animi est aliquid a, laborum consequuntur! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque, obcaecati facilis vel adipisci odit amet voluptas consequatur reiciendis dolores. Tenetur dicta, iusto ea ipsa quis repellat numquam enim quae perspiciatis.</p>
				<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, voluptatem, laudantium reiciendis voluptate illum error quisquam eum iure odio ipsum temporibus corrupti doloribus itaque animi est aliquid a, laborum consequuntur! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque, obcaecati facilis vel adipisci odit amet voluptas consequatur reiciendis dolores. Tenetur dicta, iusto ea ipsa quis repellat numquam enim quae perspiciatis.</p>
				<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, voluptatem, laudantium reiciendis voluptate illum error quisquam eum iure odio ipsum temporibus corrupti doloribus itaque animi est aliquid a, laborum consequuntur! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque, obcaecati facilis vel adipisci odit amet voluptas consequatur reiciendis dolores. Tenetur dicta, iusto ea ipsa quis repellat numquam enim quae perspiciatis.</p>
				<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, voluptatem, laudantium reiciendis voluptate illum error quisquam eum iure odio ipsum temporibus corrupti doloribus itaque animi est aliquid a, laborum consequuntur! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque, obcaecati facilis vel adipisci odit amet voluptas consequatur reiciendis dolores. Tenetur dicta, iusto ea ipsa quis repellat numquam enim quae perspiciatis.</p>
				<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, voluptatem, laudantium reiciendis voluptate illum error quisquam eum iure odio ipsum temporibus corrupti doloribus itaque animi est aliquid a, laborum consequuntur! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque, obcaecati facilis vel adipisci odit amet voluptas consequatur reiciendis dolores. Tenetur dicta, iusto ea ipsa quis repellat numquam enim quae perspiciatis.</p>
				<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, voluptatem, laudantium reiciendis voluptate illum error quisquam eum iure odio ipsum temporibus corrupti doloribus itaque animi est aliquid a, laborum consequuntur! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque, obcaecati facilis vel adipisci odit amet voluptas consequatur reiciendis dolores. Tenetur dicta, iusto ea ipsa quis repellat numquam enim quae perspiciatis.</p>
				<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, voluptatem, laudantium reiciendis voluptate illum error quisquam eum iure odio ipsum temporibus corrupti doloribus itaque animi est aliquid a, laborum consequuntur! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque, obcaecati facilis vel adipisci odit amet voluptas consequatur reiciendis dolores. Tenetur dicta, iusto ea ipsa quis repellat numquam enim quae perspiciatis.</p>
				<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, voluptatem, laudantium reiciendis voluptate illum error quisquam eum iure odio ipsum temporibus corrupti doloribus itaque animi est aliquid a, laborum consequuntur! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque, obcaecati facilis vel adipisci odit amet voluptas consequatur reiciendis dolores. Tenetur dicta, iusto ea ipsa quis repellat numquam enim quae perspiciatis.</p>
				<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, voluptatem, laudantium reiciendis voluptate illum error quisquam eum iure odio ipsum temporibus corrupti doloribus itaque animi est aliquid a, laborum consequuntur! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque, obcaecati facilis vel adipisci odit amet voluptas consequatur reiciendis dolores. Tenetur dicta, iusto ea ipsa quis repellat numquam enim quae perspiciatis.</p>
				<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, voluptatem, laudantium reiciendis voluptate illum error quisquam eum iure odio ipsum temporibus corrupti doloribus itaque animi est aliquid a, laborum consequuntur! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque, obcaecati facilis vel adipisci odit amet voluptas consequatur reiciendis dolores. Tenetur dicta, iusto ea ipsa quis repellat numquam enim quae perspiciatis.</p>
				<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, voluptatem, laudantium reiciendis voluptate illum error quisquam eum iure odio ipsum temporibus corrupti doloribus itaque animi est aliquid a, laborum consequuntur! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque, obcaecati facilis vel adipisci odit amet voluptas consequatur reiciendis dolores. Tenetur dicta, iusto ea ipsa quis repellat numquam enim quae perspiciatis.</p>
				<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, voluptatem, laudantium reiciendis voluptate illum error quisquam eum iure odio ipsum temporibus corrupti doloribus itaque animi est aliquid a, laborum consequuntur! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque, obcaecati facilis vel adipisci odit amet voluptas consequatur reiciendis dolores. Tenetur dicta, iusto ea ipsa quis repellat numquam enim quae perspiciatis.</p>
				<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, voluptatem, laudantium reiciendis voluptate illum error quisquam eum iure odio ipsum temporibus corrupti doloribus itaque animi est aliquid a, laborum consequuntur! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque, obcaecati facilis vel adipisci odit amet voluptas consequatur reiciendis dolores. Tenetur dicta, iusto ea ipsa quis repellat numquam enim quae perspiciatis.</p>
				<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, voluptatem, laudantium reiciendis voluptate illum error quisquam eum iure odio ipsum temporibus corrupti doloribus itaque animi est aliquid a, laborum consequuntur! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque, obcaecati facilis vel adipisci odit amet voluptas consequatur reiciendis dolores. Tenetur dicta, iusto ea ipsa quis repellat numquam enim quae perspiciatis.</p>
			</div>
		</motion.section>
	)
}

